version: "3.9"
services:
  app:
    image: trekkie:latest
    command: ["./bin/start_process.sh"]
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/root/.ssh
    environment:
      - APP_ROLE=app
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_PASSWORD=dbpasswd
      - DB_USER=postgres
      - SECRET_KEY_BASE
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: dbpasswd
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./tmp/db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
